DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS trade;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE trade (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  date DATE NOT NULL,
  pare TEXT NOT NULL,
  amount INTEGER NOT NULL,
  result INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);